### ISSUE TITLE
Décima lição - Aula 28-a-33 (OO - Construtores, encapsulamento e sobrecarga)

### ISSUE THREAD

**Issue by cadullira** [cadullira/javou#78]
Reescreva os exercícios anteriores, criando todos os atributos do tipo privado, métodos getters e setters e construtores. Os métodos que serão utilizados pela classe de teste devem ser públicos. Se necessário, crie métodos privados como auxiliares para organizar melhor o código fonte também.

- [ ] Exercício da lámpada refs #67 #74 
- [ ] Exercício da conta corrente refs #72 #75 
- [ ] Exercício do aluno ref #76 
- [ ] Exercício do jogo da velha refs #67 #77
